let fächer = ["lk1", "lk2", "pf1", "pf2", "pf3", "gk1", "gk2", "gk3"];
let gkAnzahl = 3;
let lk1q = 0;
let lk2q = 0;
let pf1q = 0;
let pf2q = 0;
let pf3q = 0;
let gk1q = 0;
let gk2q = 0;
let gk3q = 0;
let gk4q = 0;
let gk5q = 0;
let gk6q = 0;
let gk7q = 0;
let gk8q = 0;
let gk9q = 0;
let gk10q = 0;
let gk11q = 0;
let gk12q = 0;
let gk13q = 0;
let gk14q = 0;
let lk1abi = 0;
let lk2abi = 0;
let pf1abi = 0;
let pf2abi = 0;
let pf3abi = 0;
let anzahlGK = 3;
let result = "";

/*
localStorage.setItem("fächer", fächer);
localStorage.setItem("lk1q", lk1q);
localStorage.setItem("lk2q", lk2q);
localStorage.setItem("pf1q", pf1q);
localStorage.setItem("pf2q", pf2q);
localStorage.setItem("pf3q", pf3q);
localStorage.setItem("gk1q", gk1q);
localStorage.setItem("gk2q", gk2q);
localStorage.setItem("gk3q", gk3q);
localStorage.setItem("gk4q", gk4q);
localStorage.setItem("gk5q", gk5q);
localStorage.setItem("gk6q", gk6q);
localStorage.setItem("gk7q", gk7q);
localStorage.setItem("gk8q", gk8q);
localStorage.setItem("gk9q", gk9q);
localStorage.setItem("gk10q", gk10q);
localStorage.setItem("gk11q", gk11q);
localStorage.setItem("gk12q", gk12q);
localStorage.setItem("gk13q", gk13q);
localStorage.setItem("gk14q", gk14q);
localStorage.setItem("lk1abi", lk1abi);
localStorage.setItem("lk2abi", lk2abi);
localStorage.setItem("pf1abi", pf1abi);
localStorage.setItem("pf2abi", pf2abi);
localStorage.setItem("pf3abi", pf3abi);
localStorage.setItem("anzahlGK", anzahlGK);
localStorage.setItem("result", result);
*/